QAP-62 Check number of buying cabel
AndriiMyronenko418/QualityAssuranceProfessors pull request #28
Opened 2022-07-11 13:06 UTC by Tsibatyuk

2022-07-11 14:29 UTC, YevheniiBond approved these changes

2022-07-11 16:17 UTC, AndriiMyronenko418 requested changes

2022-07-11 19:13 UTC, Safron1ta2 approved these changes

2022-07-12 08:55 UTC, AndriiMyronenko418 approved these changes

2022-07-12 08:55 UTC, Tsibatyuk commented on src/test/java/TSibatyykEvhenii/Pages/Epicentr/SearchResult.java
> +    }
fixed

2022-07-12 08:56 UTC, merged