Change location tests
AndriiMyronenko418/QualityAssuranceProfessors pull request #3
Opened 2022-07-06 09:08 UTC by Safron1ta2

2022-07-06 11:17 UTC, Wolmeright approved these changes

2022-07-09 13:46 UTC, AndriiMyronenko418 requested changes

2022-07-09 13:46 UTC, AndriiMyronenko418 commented on src/test/java/SafroN/Tests/ChangeLocationTestPositive.java
> +        hotlineHeaderViewHelper.getLocationText();
1. Rename test1() method, please
2. Group objects of the classes together at the top of the test1() method
3. Remove empty lines between steps (including openUrl() method)

2022-07-09 13:46 UTC, AndriiMyronenko418 commented on src/test/java/SafroN/Tests/ChangeLocationTestPositive.java
> +    //enter the correct location
Remove comment

2022-07-09 13:46 UTC, AndriiMyronenko418 commented on src/test/java/SafroN/Tests/ChangeLocationTestNegative.java
> +
1. Delete comment (line 11)
1. Rename test1() method, please
2. Group objects of the classes together at the top of the test1() method
3. Remove empty lines between steps (including openUrl() method)
4. Remove empty line (line 24)

2022-07-09 13:46 UTC, AndriiMyronenko418 commented on src/test/java/SafroN/Pages/HotlineLocationViewElements.java
> +    private static final String SEARCH_LOCATION_FIELD = "//div[@class='m_b-lg']//input[@class='field']";
Add empty line before variables

2022-07-09 13:46 UTC, AndriiMyronenko418 commented on src/test/java/SafroN/Pages/HotlineHeaderViewHelper.java
> +    private String location;
Add empty line before variable

2022-07-09 13:46 UTC, AndriiMyronenko418 commented on src/test/java/SafroN/Pages/HotlineHeaderViewElements.java
> +    public WebElement locationBtnKyiv(){
add empty line between the methods

2022-07-15 08:34 UTC, closed without merging