test cart
AndriiMyronenko418/QualityAssuranceProfessors pull request #35
Opened 2022-07-12 11:50 UTC by Safron1ta2

2022-07-12 13:59 UTC, Wolmeright requested changes

2022-07-12 13:59 UTC, Wolmeright commented on src/test/java/Safron/MLB/Tests/TestCart.java
> +
Please, delete empty line

2022-07-12 19:01 UTC, Safron1ta2 commented on src/test/java/Safron/MLB/Pages/MLBProductPageHelper.java
> +import java.time.Duration;
fixed

2022-07-12 19:02 UTC, Safron1ta2 commented on src/test/java/Safron/MLB/Tests/TestCart.java
> +
why?

2022-07-13 15:21 UTC, Tsibatyuk approved these changes

2022-07-13 15:21 UTC, Tsibatyuk approved these changes

2022-07-14 11:29 UTC, YevheniiBond approved these changes

2022-07-14 13:07 UTC, Wolmeright approved these changes

2022-07-14 17:47 UTC, merged