Eldorado e2e add and remove from cart
AndriiMyronenko418/QualityAssuranceProfessors pull request #48
Opened 2022-07-14 06:07 UTC by YevheniiBond

2022-07-14 08:18 UTC, Wolmeright requested changes

2022-07-14 08:18 UTC, Wolmeright commented on src/test/java/YevheniiBondarenko/Tests/Pages/EldoradoWebElementsPage.java
> +
Delete empty line, please)

2022-07-14 08:18 UTC, Wolmeright commented on src/test/java/YevheniiBondarenko/Tests/Pages/EldoradoWebElementsPage.java
> +
Delete empty lines, please)

2022-07-14 08:18 UTC, Wolmeright commented on src/test/java/YevheniiBondarenko/Tests/Tests/EldoradoE2EBuyingMobilePhone.java
> +
Delete empty lines, please)

2022-07-14 12:01 UTC, YevheniiBond reviewed
Done

2022-07-14 12:40 UTC, AndriiMyronenko418 requested changes

2022-07-14 12:40 UTC, AndriiMyronenko418 commented on src/test/java/YevheniiBondarenko/Tests/Tests/EldoradoE2EBuyingMobilePhone.java
> +    public void eldoradoE2EAddAndRemoveFromCart(){
add an empty line between 13 and 14

2022-07-14 13:09 UTC, Wolmeright commented on src/test/java/YevheniiBondarenko/Tests/Pages/EldoradoWebElementsPage.java
> +    public List<WebElement> deleteItemsFromCart(){return $$(DELETE_ITEMS_FROM_CART);}
use CTRL+ALT+L

2022-07-14 14:30 UTC, Wolmeright approved these changes

2022-07-14 15:09 UTC, Tsibatyuk approved these changes

2022-07-14 16:48 UTC, YevheniiBond commented on src/test/java/YevheniiBondarenko/Tests/Pages/EldoradoWebElementsPage.java
> +
+

2022-07-14 16:49 UTC, YevheniiBond commented on src/test/java/YevheniiBondarenko/Tests/Pages/EldoradoWebElementsPage.java
> +
+++

2022-07-14 16:49 UTC, YevheniiBond commented on src/test/java/YevheniiBondarenko/Tests/Pages/EldoradoWebElementsPage.java
> +    public List<WebElement> deleteItemsFromCart(){return $$(DELETE_ITEMS_FROM_CART);}
+++

2022-07-14 16:49 UTC, YevheniiBond commented on src/test/java/YevheniiBondarenko/Tests/Tests/EldoradoE2EBuyingMobilePhone.java
> +    public void eldoradoE2EAddAndRemoveFromCart(){
+++

2022-07-15 08:24 UTC, YevheniiBond commented on src/test/java/YevheniiBondarenko/Tests/Tests/EldoradoE2EBuyingMobilePhone.java
> +
+++

2022-07-15 08:30 UTC, AndriiMyronenko418 approved these changes

2022-07-15 08:33 UTC, merged